### ISSUE TITLE
Missing required "response_type" parameter on authorization URL

### ISSUE THREAD

**Issue by rs** [fireteam/curlish#1]
I tried your command with Dailymotion which is stricter than Facebook regarding the spec:

```
"dailymotion": {
  "extra_headers": {},
  "request_token_params": {
    "scope": "email"
  },
  "authorize_url": "https://api.dailymotion.com/oauth/authorize",
  "base_url": "https://api.dailymotion.com/",
  "client_id": "xxx",
  "client_secret": "xxx",
  "grant_type": "authorization_code",
  "access_token_url": "/oauth/token"
},
```

It generates `https://api.dailymotion.com/oauth/authorize?scope=email&redirect_uri=http%3A%2F%2F127.0.0.1%3A62231%2F&client_id=xxx`.

The server then responds:

```
invalid_request Missing `response_type' parameter.
```

The spec says:

> 3.1.1.  Response Type
> 
>    The authorization endpoint is used by the authorization code grant
>    type and implicit grant type flows.  The client informs the
>    authorization server of the desired grant type using the following
>    parameter:
> 
>    response_type
>          REQUIRED.  The value MUST be one of "code" for requesting an
>          authorization code as described by Section 4.1.1, "token" for
>          requesting an access token (implicit grant) as described by
>          Section 4.2.1, or a registered extension value as described by
>          Section 8.4.
> 
>    Extension response types MAY contain a space-delimited (%x20) list of
>    values, where the order of values does not matter (e.g. response type
>    "a b" is the same as "b a").  The meaning of such composite response
>    types is defined by their respective specifications.
> 
>    **If an authorization request is missing the "response_type" parameter,
>    or if the response type is not understood, the authorization server
>    MUST return an error response as described in Section 4.1.2.1.**

**Comment by mitsuhiko** [comment]
Fixed in the new version. You can also just change `request_token_params` to send this value but I now enforced it for all requests since it really should be part of the flow.

**Comment by rs** [comment]
Works well, thx
