### ISSUE TITLE
Installation command creates ~/.bin inside my user's folder

### ISSUE THREAD

**Issue by iezg** [fireteam/curlish#9]
I run the installation command as written in the documentation

``` console
$ curl -L http://bit.ly/curlish | bash
```

but instead of creating a .bin folder inside my user's home, I get a ~/.bin inside it:

``` console
/Users/myuser/~/.bin
```

I'm using OSX 10.7.4 and curl 7.21.4

**Comment by mitsuhiko** [comment]
Interesting. How did you manage to get that.
